### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by fubai3** [HarleysZhang/detect_steel_number#6]
File "E:\miniconda3\envs\yolov4_tf1.14_py3.6\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'GeneratorEnqueuer.start.<locals>.data_generator_task'
{'log_to_stderr': False, 'authkey': b"\xf2'I\xb91k\xc7R\xca,fp\n\xdcV\xf8\x14[h\xd3\xf6\xe6X\xa5\xdb}E:%\xdb\xba)", 'name': 'Process-1', 'sys_path': ['E:\\Wuyf\\Project\\detect_steel_number-master\\samples\\gangjin', 'E:\\miniconda3\\envs\\yolov4_tf
1.14_py3.6\\python36.zip', 'E:\\miniconda3\\envs\\yolov4_tf1.14_py3.6\\DLLs', 'E:\\miniconda3\\envs\\yolov4_tf1.14_py3.6\\lib', 'E:\\miniconda3\\envs\\yolov4_tf1.14_py3.6', 'E:\\miniconda3\\envs\\yolov4_tf1.14_py3.6\\lib\\site-packages', 'E:\\minico
nda3\\envs\\yolov4_tf1.14_py3.6\\lib\\site-packages\\mask_rcnn-2.1-py3.6.egg', 'E:\\Wuyf\\Project\\detect_steel_number-master'], 'sys_argv': ['gangjin.py', 'train', '--dataset=./datasets/', '--weights=coco'], 'orig_dir': 'E:\\Wuyf\\Project\\detect_s
teel_number-master\\samples\\gangjin', 'dir': 'E:\\Wuyf\\Project\\detect_steel_number-master\\samples\\gangjin', 'start_method': 'spawn', 'init_main_from_path': 'E:\\Wuyf\\Project\\detect_steel_number-master\\samples\\gangjin\\gangjin.py'}
E:\miniconda3\envs\yolov4_tf1.14_py3.6\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) /
 '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
E:\miniconda3\envs\yolov4_tf1.14_py3.6\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) /
 '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
E:\miniconda3\envs\yolov4_tf1.14_py3.6\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) /
 '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
E:\miniconda3\envs\yolov4_tf1.14_py3.6\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) /
 '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
E:\miniconda3\envs\yolov4_tf1.14_py3.6\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) /
 '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
E:\miniconda3\envs\yolov4_tf1.14_py3.6\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) /
 '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

(yolov4_tf1.14_py3.6) E:\Wuyf\Project\detect_steel_number-master\samples\gangjin>E:\miniconda3\envs\yolov4_tf1.14_py3.6\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of t
ype is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
E:\miniconda3\envs\yolov4_tf1.14_py3.6\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type,
(1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
E:\miniconda3\envs\yolov4_tf1.14_py3.6\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type,
(1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
E:\miniconda3\envs\yolov4_tf1.14_py3.6\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type,
(1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
E:\miniconda3\envs\yolov4_tf1.14_py3.6\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type,
(1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
E:\miniconda3\envs\yolov4_tf1.14_py3.6\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type,
(1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using TensorFlow backend.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\miniconda3\envs\yolov4_tf1.14_py3.6\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "E:\miniconda3\envs\yolov4_tf1.14_py3.6\lib\multiprocessing\spawn.py", line 117, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

Hello, how did I report this mistake on Windows? Thank you

**Comment by harleyszhang** [comment]
Maybe your input image shape is too big, you should set more small, such as (504, 1024)，can you show your gpu type.
